language: python
python:
  - "2.7"
  - "3.6"
sudo: false
cache:
  directories:
  - eggs
  - parts/node
  - downloads


matrix:
  include:
  - python: "2.7"
    env: PLONE_VERSION=4.3
  - python: "2.7"
    env: PLONE_VERSION=5.0
  - python: "2.7"
    env: PLONE_VERSION=5.1
  - python: "2.7"
    env: PLONE_VERSION=5.2
  - python: "3.6"
    env: PLONE_VERSION=5.2
  exclude:
  - python: "2.7"
  - python: "3.6"

install:
- ln -s plone-$PLONE_VERSION.x.cfg buildout.cfg
- pip install -r requirements.txt
- buildout annotate
- buildout -Nq
script:
- bin/test
